name: CI
on:
  push:
    branches:
      - master
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Run tests and publish test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install responses
          python3 ${{ github.workspace }}/setup.py install
          python3 install coverage
      - name: Run Tests
        run: |
          python3 -m unittest
          python3 -m coverage report
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
